### ISSUE TITLE
BCH Support?

### ISSUE THREAD

**Issue by Francewhoa** [soundasleep/openclerk#29]
Hi there :)

Do both Openclerk and cryptfolio.com support Bitcoin Cash (BCH)?

I tried the instructions at https://support.cryptfolio.com/i19-bitcoin-cash-addresses But it did not work. 

**Steps to reproduce**

1. Sign-up at https://cryptfolio.com with a free account to try it
1. Log-in at https://cryptfolio.com
1. Go to https://cryptfolio.com/portfolios
1. This error message is return
> Could not find translated module for 'portfolios'
![error---2017-12-30---18 13 35---selection_001---francewhoa](https://user-images.githubusercontent.com/119942/34458686-78714d8e-ed90-11e7-8960-9915048c12fa.jpg)
1. The nexpected result is that the user would be able to use BCH

BTW I first tried to create a ticket at http://redmine.jevon.org but it didn't work. Today I sent a ticket with the steps to reproduce this.

Cheers,

Francewhoa

**Comment by soundasleep** [comment]
Hi! Yes this is on the new CryptFolio preview site, which isn't live yet - would you like to try it out at https://preview.cryptfolio.com? :)

**Comment by Francewhoa** [comment]
> Hi! Yes this is on the new CryptFolio preview site, which isn't live yet
Thanks :) 

> Would you like to try it out at https://preview.cryptfolio.com? :)
Yes conditional to be fully open-source now, and with a commitment to remain open source in the future

**Comment by Francewhoa** [comment]
Closing this ticket. I created a new ticket about the other topic about interest in open source model.
