### ISSUE TITLE
ETH / ADA / ETC support

### ISSUE THREAD

**Issue by Pastafarianist** [soundasleep/openclerk#30]
Currently ETH and ADA are at top 3 and top 5 by market cap according to https://coinmarketcap.com/, yet neither are supported (ETC is 18th). Can they be added?

**Comment by soundasleep** [comment]
They can definitely be added to openclerk, but for now I'm putting all of my focus on the new CryptFolio (which supports these three coins already). Would you like to try it out? https://preview.cryptfolio.com

**Comment by Pastafarianist** [comment]
Thanks for the link. Unfortunately, I wasn't able to find ADA in the list of supported coins with the new version. Are you sure it is supported?

**Comment by soundasleep** [comment]
Hmm, it should be: https://preview.cryptfolio.com/currencies/ada It's an "unknown" type though, so it won't list in the "cryptocurrencies" list, rather the non-cryptocurrencies list.

Regardless I've updated it to be listed as a cryptocurrency now, so it should definitely appear. Thank you!
