### ISSUE TITLE
Installing on shared host

### ISSUE THREAD

**Issue by Flurrywinde** [soundasleep/openclerk#32]
Is it possible to install this on a shared host where I don't have shell access? I uploaded all files, but when I access the `site/` directory with a browser, it says:

> Failed opening required '/home/me/public_html/cryptfolio/inc/../vendor/autoload.php'

**Comment by soundasleep** [comment]
Hello! It looks like you're having an issue with composer, I haven't tried to install composer on a host without shell access. Maybe you can bundle up the vendor/ directory from your local installation, and upload all of that?

(I wouldn't recommend putting this onto a host without shell access.)
